version: '3.8'

services:
  vue-app:
    build: .
    image: maximecoriton/mon-application:latest
    ports:
      - "80:80"
    depends_on:
      - mysql-db
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: yourdatabase

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdatabase
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
